src/fullctl/django/fields/__init__.py
src/fullctl/django/fields/service_bridge/__init__.py
src/fullctl/django/models/abstract/__init__.py
src/fullctl/django/models/abstract/service_bridge.py
src/fullctl/django/rest/mixins.py
src/fullctl/django/rest/views/service_bridge.py
src/fullctl/django/static/common/app.css
src/fullctl/django/static/common/app.js
src/fullctl/service_bridge/client.py
src/fullctl/service_bridge/devicectl.py
src/fullctl/service_bridge/nautobot.py
src/fullctl/utils/__init__.py

devicectl servicebridge
nautobot servicebridge
servicebridge write ops

devicectl prep

---

src/fullctl/django/settings/default.py

Set `CSRF_FROM_SESSIONS` to `True`.

Security update

---

docs/api_docs.md
poetry.lock
pyproject.toml
src/fullctl/django/rest/api_schema.py
src/fullctl/django/rest/decorators.py
src/fullctl/django/rest/fields.py
src/fullctl/django/rest/serializers/__init__.py
src/fullctl/django/rest/serializers/service_bridge.py
src/fullctl/django/rest/views/account.py
src/fullctl/django/rest/views/service_bridge.py
src/fullctl/django/rest/views/usage.py
src/fullctl/django/templates/common/apidocs/redoc.html
src/fullctl/django/templates/common/apidocs/swagger.html
src/fullctl/django/urls.py
src/fullctl/django/views/api_schema.py

fixes openapi doc generation from django-rest-framework schema / views

Openapi docs

---

src/fullctl/django/models/abstract/service_bridge.py
src/fullctl/django/rest/views/service_bridge.py
src/fullctl/django/settings/__init__.py
src/fullctl/django/static/common/20c/twentyc.rest.js
src/fullctl/service_bridge/client.py
src/fullctl/service_bridge/devicectl.py
src/fullctl/service_bridge/sot.py

required for peerctl devicectl integration

devicectl service bridge additions

---

.github/workflows/codeql.yml
src/fullctl/django/decorators.py

fixes issues with impersonation

fix issue where impersonating a user would result in a 404 on their org

---

src/fullctl/service_bridge/client.py

adds response data to service bridge errors

Service bridge error info

---

src/fullctl/django/static/common/20c/twentyc.rest.js
src/fullctl/django/static/common/v2/themes/dark.css
src/fullctl/django/templates/common/v2/app/base.html

- support clickable urls from REST api error message
- call to action when access is missing and trial has been used

billing fixes

---

.github/workflows/tests.yml
src/fullctl/service_bridge/pdbctl.py

- add pdbctl.IXLanPrefix service bridge object

20230215 fixes

---

src/fullctl/django/rest/serializers/aaactl_sync.py
src/fullctl/service_bridge/aaactl.py
src/fullctl/service_bridge/client.py
src/fullctl/service_bridge/devicectl.py
src/fullctl/service_bridge/ixctl.py
src/fullctl/service_bridge/pdbctl.py
src/fullctl/service_bridge/peerctl.py
src/fullctl/service_bridge/prefixctl.py

fixes issues with double `//` in and at the end of service api urls

Service api url fix

---

src/fullctl/django/static/common/v2/app.js
src/fullctl/django/static/common/v2/themes/dark.css

Clicking the th.checkbox-cell, td.checkbox-cell that the checkbox is in will toggle the checkbox

Checkbox Color/ functionality update

---

src/fullctl/django/static/common/v2/app.css
src/fullctl/django/static/common/v2/app.js
src/fullctl/django/templates/common/v2/app/base.html
src/fullctl/django/templates/common/v2/app/cross-promote-trials.html
src/fullctl/django/urls.py

contains the fixes from #131 
also introduces service cross promotional features
needs https://github.com/fullctl/aaactl/pull/106 merged

product trial cross promotion

---

Ctl/dev/docker-compose.yml
src/fullctl/django/models/abstract/meta.py

fixes issue where meta data would not be written if it was empty even though the data changed from the previous entry.
e.g., going from reputation issues to all issues fixed

Fix meta data

---

src/fullctl/django/autocomplete/devicectl.py

fix issue with device autocomplete when port is not connected to a device

20230516 fixes

---

src/fullctl/django/autocomplete/devicectl.py
src/fullctl/django/static/common/v2/app.css
src/fullctl/django/static/common/v2/app.js
src/fullctl/django/templates/common/v2/app/base.html

notifications system to quickly alert UX relevant information to the user (session expired etc.)

20230524 fixes

---

src/fullctl/django/static/common/v2/graph.js

- fixes y and x axis label distribution in traffic graphs

fix axis label counts to avoid squishing

---

src/fullctl/django/models/abstract/meta.py

- immediate retries until limit is reached
- dont treat 429 responses with the normal cache expiry they need to be retried much quicker (5 mins)

handle 429

---

src/fullctl/django/static/common/20c/twentyc.rest.js
src/fullctl/django/static/common/v2/app.css
src/fullctl/django/static/common/v2/app.js
src/fullctl/django/static/common/v2/themes/dark.css

- Fix select2 styles
- Fix confirm pop-up popping up when not needed
- Clean up logic of code

20230703 UX fixes

---

src/fullctl/django/rest/serializers/aaactl_sync.py
src/fullctl/django/rest/views/aaactl_sync.py

allow user creation through service bridge (up until now only update sync would work)
needed for mass user import

sync new user creation through service bridge

---

src/fullctl/django/static/common/20c/twentyc.rest.js
src/fullctl/django/static/common/v2/app.css

- add count panel styles (.infobar)
- add confirm option for unchecking a Checkbox widget

20230710 UX

---

src/fullctl/django/static/common/v2/app.js
src/fullctl/django/static/common/v2/graph.js
src/fullctl/graph/mrtg/rrd.py
src/fullctl/graph/render/traffic.py

- assume mrtg data comes in as bytes and convert to bits before storing in rrd
- fix y-axis labeling in rendered and js graphs
- smooth long duration rendered graphs
- fix total ix traffic aggregation issues

graph fixes 20230725

---

src/fullctl/service_bridge/devicectl.py

service bridge function to push referee report to devicectl

Devicectl referee reports

---

poetry.lock
pyproject.toml
src/fullctl/django/settings/__init__.py
tests/django_tests/test_setting.py

related: https://github.com/fullctl/aaactl/pull/160

add django-cors-headers

---

src/fullctl/django/context_processors.py
src/fullctl/django/management/commands/fullctl_local_setup.py
src/fullctl/django/templates/common/v2/app/base.html

Currently targeting draft-pr-branch for review
Adds some fixes to make local auth work again, plus a quick setup script to help with installation ease of local instances.

20240213 local auth fixes

---

CHANGELOG.md
CHANGELOG.yaml
src/fullctl/django/health_check.py
src/fullctl/django/models/abstract/meta.py
src/fullctl/django/views/__init__.py
tests/django_tests/test_views.py

- changes the health view to be extendible by the service and/or installed addons
- fixes issue with meta data cache expiry if expiry was set to never and api throttling was encountered

extendible health check view and meta cache expiry fixes

---

.github/workflows/tests.yml
CHANGELOG.md
CHANGELOG.yaml
tox.ini

support already had been removed from pyproject.toml

remove py3.8 tests 

---

src/fullctl/django/tasks/__init__.py
tests/django_tests/test_commands.py
tests/django_tests/testapp/models.py

This is an implementation for the CU bug:
https://app.clickup.com/t/14289126/FC-3420

Unresolvable task op should not cause a hard failure

---

src/fullctl/django/context_processors.py

Part of the implementation for making css field a json:
https://app.clickup.com/t/14289126/FC-3272

fix: Make the CSS field in DJANGO ADMIN BRANDING a JSON field
